[package]
name = "espipe"
description = "A minimalist command-line utility to pipe documents from a file or I/O stream into an Elasticsearch cluster."
repository = "https://github.com/VimCommando/espipe"
version = "0.1.3"
edition = "2024"
rust-version = "1.88"
license = "AGPL-3.0"

[dependencies]
base64 = "0.22.1"
clap = { version = "^4.5.21", features = ["derive"] }
csv = "^1.3.1"
elasticsearch = "^9.1.0-alpha.1"
env_logger = "^0.11.5"
eyre = "^0.6.12"
fluent-uri = "^0.4.1"
futures = "^0.3.31"
log = "^0.4.22"
serde = { version = "^1.0.199", features = ["derive"] }
serde_json = "^1.0.133"
serde_yaml = "^0.9.34"
tokio = "^1.41.1"
url = { version = "^2.5.4", features = ["serde"] }
